### ISSUE TITLE
MSVC build not working due to problematic usage of stat struct

### ISSUE THREAD

**Issue by alberthdev** [antony-jr/QArchive#13]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
I'm building the latest QArchive on MSVC, and it looks like it's failing to compile due to the use of Linux stat struct isms, e.g.:

```
..\gui\qt\QArchive\src\QArchive.cc(1827): error C2039: 'st_blksize': is not a member of 'stat'
..\gui\qt\QArchive\src\QArchive.cc(1828): error C2039: 'st_blocks': is not a member of 'stat'
..\gui\qt\QArchive\src\QArchive.cc(1836): error C2039: 'st_atim': is not a member of 'stat'
..\gui\qt\QArchive\src\QArchive.cc(1836): error C2228: left of '.tv_sec' must have class/struct/union
..\gui\qt\QArchive\src\QArchive.cc(1837): error C2039: 'st_mtim': is not a member of 'stat'
..\gui\qt\QArchive\src\QArchive.cc(1837): error C2228: left of '.tv_sec' must have class/struct/union
..\gui\qt\QArchive\src\QArchive.cc(1838): error C2039: 'st_ctim': is not a member of 'stat'
..\gui\qt\QArchive\src\QArchive.cc(1838): error C2228: left of '.tv_sec' must have class/struct/union
..\gui\qt\QArchive\src\QArchive.cc(1888): error C3536: 'lastAccessT': cannot be used before it is
..\gui\qt\QArchive\src\QArchive.cc(1894): error C3536: 'lastModT': cannot be used before it is
..\gui\qt\QArchive\src\QArchive.cc(1900): error C3536: 'lastStatusModT': cannot be used before it is
```

**Ways to Reproduce the issue (optional):**
Build under MSVC to see the issue.

**Comment by antony-jr** [comment]
@alberthdev Did you include all the needed header files , please see https://github.com/antony-jr/QArchive/issues/7. If that did not work for you then please wait , It may take some time to cleanup the mess.

**Comment by antony-jr** [comment]
@alberthdev Thank you. I never tested the sources on windows. (Its kinda of a pain to even compile libarchive in windows ) , Maybe in near future , We will need to include some windows CI.
