### ISSUE TITLE
No API for compress dir

### ISSUE THREAD

**Issue by alvin-xian** [antony-jr/QArchive#21]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
No API for compress dir, it's important
**Ways to Reproduce the issue (optional):**
No need

**Comment by alvin-xian** [comment]
I had build archive lib&dll by msvc2013.
if u need , i would send u

**Comment by antony-jr** [comment]
> No API for compress dir, it's important

@alvin-xian Do you want a method in ```QArchive::DiskCompressor``` to recursively add files to the archive from a directory??

**Comment by antony-jr** [comment]
in my opinion you can do it manually but I think its a nice feature to have, I will add it in the next version. Thanks for the suggestion.

**Comment by antony-jr** [comment]
@alvin-xian **v2.1.0** now has a way to add directory for compression. **Now addFiles() method will automatically add directories.**

```
QArchive::DiskCompressor Compressor("Test.7z");
Compressor.addFiles(/*Entry Name=*/ "MyDir", /*Directory or File to Compress=*/ "SomeDirInDisk/");

QObject::connect(&Compressor, &QArchive::DiskCompressor::finished, &app, &QCoreApplication::quit);

Compressor.start();
```
