### ISSUE TITLE
Better progress report for DiskCompressor

### ISSUE THREAD

**Issue by longseespace** [antony-jr/QArchive#23]
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
The current `percentageDone` implementation is not very useful (or even incorrect) in term of UX. It is calculated as `((n_TotalEntries - m_ConfirmedFiles->size())*100)/n_TotalEntries)` (https://github.com/antony-jr/QArchive/blob/master/src/qarchivediskcompressor_p.cc#L543)

I can see some issues with this:
1. Unnecessary: the calculation can be done in application code
2. Incorrect: the `percentageDone` does not represent actual percentage of compression done. For example I would want to calculate time remaining. Unless all files have equal size, the `percentageDone` would never be correct
3. Useless in case the compressor contains only 1 file (the signal emit once, after the file is fully compressed)

My quick & dirty solution is to calculate `totalDataSize` and `processedDataSize`, then calculate `percentageDone` based on that. To solve the issue 3 above, I added a `QElapsedTimer` and emit progress every 1 second. Something like this:

```
QElapsedTimer timer;
timer.start();

len = file->read(buff, sizeof(buff));
while (len > 0) {
  archive_write_data(m_ArchiveWrite.data(), buff, len);

  processedDataSize += len;

  if (timer.hasExpired(1000)) {
    emit progress(QString(node.second),
                  (n_TotalEntries - m_ConfirmedFiles->size()),
                  n_TotalEntries,
                  (float(processedDataSize) * 100) / totalDataSize);

    timer.restart();
  }

  len = file->read(buff, sizeof(buff));
}
file->close();
```

Now my question is would this affect overall performance? In term of public API, should we add a separated signal to report this progress or it's ok to use the current one?

Will send a PR soon.

**Comment by antony-jr** [comment]
> Now my question is would this affect overall performance? In term of public API, should we add a separated signal to report this progress or it's ok to use the current one?

@longseespace I think the hardest part is getting the total data size, we would have to walk through every file but I think this can be efficiently done. So I think the performance would not be effected at all.. But I personally think we don't need a elapsed timer since the loop is going to loop every second or less than that...

**Comment by longseespace** [comment]
Without the timer it would emit a lot and in my app, it hangs. So I think we still need it. Let me polish the code and send a PR

**Comment by antony-jr** [comment]
> Without the timer it would emit a lot and in my app, it hangs. So I think we still need it. Let me polish the code and send a PR

Okay. Thanks for the PR.

**Comment by longseespace** [comment]
@antony-jr While working on the PR I realize that it's easy to calculate the `bytesTotal` for `DiskCompressor` but not so easy for `DiskExtractor`. Do you have any idea on how to calculate it?
