### ISSUE TITLE
Compressed file is not closed after decompression

### ISSUE THREAD

**Issue by d-divita** [antony-jr/QArchive#26]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
The compressed file, after being correctly unzipped, is not closed i.e. it can't be renamed/deleted from the file explorer

**Ways to Reproduce the issue (optional):**
[Windows 10, Qt 5.14.1, mingw-64bit]
Initialize the extractor:
```
auto Extractor = new QArchive::DiskExtractor(file_path, dir, this, false);
Extractor->start();
```

then when the finished signal has been emitted, if I try to rename the file I get an error from Windows (file already in use by my_app.exe)

**Comment by antony-jr** [comment]
Okay Will look into it.

**Comment by antony-jr** [comment]
@d-divita Can you please verify this on the latest commit?

**Comment by d-divita** [comment]
> @d-divita Can you please verify this on the latest commit?

I confirm that now the file is released correctly. Thank you very much for the fast fix.
