### ISSUE TITLE
Reporting decompression progress in bytes

### ISSUE THREAD

**Issue by d-divita** [antony-jr/QArchive#27]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
For what I understood, the "progress" signal is fired after each file in the archive has been completely decompressed, so, if there is just one file in the archive, the progress is reported at the end of the whole decompression.
My question is if there is a way to have a signal firing every "x" seconds reporting the bytes decompressed at that time so that it is possible to calculate the decompression percentage progress of a single file. The files I work with take about 1min each to be unzipped and from the user perspective there is no clue about the decompression status.

**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
I think I've done this, I will check the source and ping back asap.

**Comment by antony-jr** [comment]
@d-divita Can you please try the latest commit??

**Comment by d-divita** [comment]
Now it works exactly the way I needed it to, thank you!
