### ISSUE TITLE
Cancel/pause behaviour

### ISSUE THREAD

**Issue by d-divita** [antony-jr/QArchive#28]
**Select your issue type:** (check at least one)
- [x] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
I have a doubt on the cancel/pause function: I would like to be able to stop a decompression in my app, so I have a button that once pressed it calls the cancel() slot on the extractor (sample code below); I don't know if it is a bug or if I misunderstood the API functionality, but when I press the button, the extraction continues till the end and after that I receive the "canceled" signal, but I expect that the extraction is immediatly aborted (or paused, the behaviour is the same with the pause() slot).

**Ways to Reproduce the issue (optional):**
```
auto Extractor = new QArchive::DiskExtractor(path, this, false); // with the last argument as true the behaviour is the same

QObject::connect(Extractor, &QArchive::DiskExtractor::progress, [&]([...]){qDebug() << "progress" << bytesProcessed*100/bytesTotal);});
QObject::connect(Extractor, &QArchive::DiskExtractor::canceled, [&](){qDebug() <<"Decompression canceled!\n";}); // <-- I get this after the whole decompression if I cancel it
QObject::connect(Extractor, &QArchive::DiskExtractor::finished, [&](){Debug() <<"Finished!\n"); });

Extractor->setCalculateProgress(true);
Extractor->getInfo();
Extractor->start();
```

then I call `Extractor->cancel();`
and I keep getting the progress until the end of extraction (which can be very long, that's why I need it to be canceled/paused), and then the canceled signal is fired.

**Comment by antony-jr** [comment]
This is because I kept the cancel and pause routine at the end of each file extraction in the archive. So for single file archives it does something strange like this. I will fix this ASAP.

**Comment by antony-jr** [comment]
Sorry for the late fix. The latest commit fixes this. Please reopen if it doesn't work for you.
