### ISSUE TITLE
Extracting archives with non-Latin1 characters is not ideal

### ISSUE THREAD

**Issue by g-fb** [antony-jr/QArchive#29]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

The output path is converted to Latin-1 https://github.com/antony-jr/QArchive/blob/master/src/qarchivediskextractor_p.cc#L602
But if the output path contains non-Latin1 characters, like japanese characters, they get turned to `?`.
`toUtf8()` should do the same without the above drawback.

**Comment by antony-jr** [comment]
You make a very good point, I will change it in the next release or you can send a pull request if you are interested.

**Comment by g-fb** [comment]
The password also uses toLatin1, should I change that too?

**Comment by antony-jr** [comment]
Yes.
