### ISSUE TITLE
Is it possible to extract LZMA zip archives with QArchive?

### ISSUE THREAD

**Issue by KGergo88** [antony-jr/QArchive#31]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Thank you for developing this project!

I have a Qt app that needs to read text based files that are compressed into a zip archive. Previously this was done with [QuaZip](https://github.com/stachenov/quazip) but recetly, the component that creates the zip files switched to LZMA compression and I need to find a new solution as this is not supported by QuaZip.

Can QArchive extract LZMA zip archives?

Here is what I tried so far:
- I took the [disk_extractor example](https://github.com/antony-jr/QArchive/blob/master/examples/disk_extractor/main.cc) and tried to extract my LZMA zip files but I get the following error:
`An error has occured :: "QArchive::ArchiveCorrupted"`

- I have also tried to extract the file with the [minitar libarray example](https://github.com/libarchive/libarchive/tree/master/examples/minitar) but it fails as well:
```bash
$ ./minitar -x -f zip_file.zip 
Unrecognized archive format
```

More details on my use case:
- OS: Ubuntu 18.04 LTS (but later the app needs to run on Windows 10 as well)
- I have build both QArray (tag: v2.0.0) and libarray (tag: v3.4.3) myself
- I can extract the files with 7Zip on Windows or with p7zip on Linux with the command (after renaming the .zip file to .7z): `p7zip -d zip_file.7z`

**Ways to Reproduce the issue (optional):**

Unfortunately I cannot send you zip files or the code that produces them but here is a Python snippet that procudes an LZMA zip with a txt file in it. I get the same error messages for these as well:

```python
import zipfile

txt_file_content = ["This is the content ", "of the file I would like to ", "compress with LZMA!"]

with zipfile.ZipFile("zip_file.zip", "w", zipfile.ZIP_LZMA) as zf:
    zf.writestr("txt_file.txt", "\n".join(txt_file_content))
```

**Comment by antony-jr** [comment]
@KGergo88 QArchive uses libarchive as the backend. But libarchive says -> Automatically handles archives compressed with gzip, bzip2, lzip, xz, lzma, or compress.  So let me check it in my system.

**Comment by antony-jr** [comment]
```
antonyjr@Liz:~/Developer/QArchive/examples/disk_extractor/build> ./extractor zip_file.zip 
ARCHIVE CONTENTS::  QJsonObject({"txt_file.txt":{"BlockSize":0,"BlockSizeUnit":"Bytes","Blocks":0,"FileName":"txt_file.txt","FileType":"RegularFile","LastAccessedTime":"Unknown","LastModifiedTime":"2020-11-19T23:28:40","LastStatusModifiedTime":"Unknown","Size":69,"SizeUnit":"Bytes"}})
[+] Starting Extractor... 
Progress( 0 / 1 ):  "txt_file.txt"  :  100 % done.
Progress( 1 / 1 ):  "txt_file.txt"  :  100 % done.
[+] Extracted File(s) Successfully!
```

@KGergo88 I can extract the file generated by your python script. So I think we can extract this type of ZIP files. I think you are missing some optional dependencies like liblzma. Also I compiled from master branch of QArchive. One way to verify if you have all libs correctly installed is compiling or installing **bsdtar** and run ```bsdtar --version``` and should have output similar to mine down below..,

```
antonyjr@Liz:~/Developer/QArchive/examples/disk_extractor/build> bsdtar --version
bsdtar 3.4.3 - libarchive 3.4.3 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.5 
```

**Comment by KGergo88** [comment]
Hello @antony-jr,

many thanks for your help! :smile:

You were right, the `liblzma-dev` package was missing on my system, only the `liblzma5` was present. I have installed it, rebuilt the liblzma and the QArchive and now the disk extractor example **works as expected**. The minitar example gives me the same error as before but that is not important.

**One more question:** is it possible to use QArchive in a way that it does not extract the files onto the disk but opens the archive and reads the files with a QIODevice class? This was possible with QuaZip and I really liked that feature becuase then I do not have to make clean-up for the extracted files.

**Comment by antony-jr** [comment]
> One more question: is it possible to use QArchive in a way that it does not extract the files onto the disk but opens the archive and reads the files with a QIODevice class? This was possible with QuaZip and I really liked that feature becuase then I do not have to make clean-up for the extracted files.

@KGergo88 You can open a Archive in Memory but the output is written to the disk. But I'm thinking about making it possible in the future. See [setArchive(QIODevice*)](https://antonyjr.in/QArchive/docs/QArchiveDiskExtractor.html#void-setarchiveqiodevice-archvie)

Please open a new issue or rename this one to keep a tab on the feature to enable extract data to memory.

**Comment by KGergo88** [comment]
Thank you for your help! I will close this issue.
