### ISSUE TITLE
Add a feature for reading an archive without having to extract the files to the disk

### ISSUE THREAD

**Issue by KGergo88** [antony-jr/QArchive#32]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
I would like to use the QArchive extracting feature to read the files in the archive without storing them to the disk.
In my use case the files would be simple text or json files in an LZMA zip archive. This issue is related to the question #31.

**Comment by antony-jr** [comment]
Let me see If I can do something. Will be keeping this issue as a tracker for that feature.

**Comment by antony-jr** [comment]
@KGergo88 As of **v2.1.0** you can now extract archives in memory.

Please see this [blog post](https://antonyjr.in/QArchive/blog/2021/06/19/Announcing-v2.1.0.html).
