### ISSUE TITLE
Read zip info - as basic infor about it.

### ISSUE THREAD

**Issue by unusual-aspect** [antony-jr/QArchive#33]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [ x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
As there is a function that as i was expect will return info about file - is return all files info.
What i sugest is have some quick and dirty function to return number of files/entries in zip file (or any other archive).
That will help to create a nice 'progress bar' - there is a process function that expose this info, but is to late for that, as extraction is already started!

Can we have something like: qint64 getEntries() - that will return just a number how many 'files' we have?

**Comment by antony-jr** [comment]
> That will help to create a nice 'progress bar' - there is a process function that expose this info, but is to late for that, as extraction is already started!

@unusual-aspect There is already a signal called [progress](https://antonyjr.in/QArchive/docs/QArchiveDiskExtractor.html#void-progressqstring-file--int-processedentries--int-totalentries--qint64-bytesprocessed-qint64-bytestotal), it only emits the exact progress when given [setCalculateProgress(true)](https://antonyjr.in/QArchive/docs/QArchiveDiskExtractor.html#void-setcalculateprogressbool-choice)

> Can we have something like: qint64 getEntries() - that will return just a number how many 'files' we have?

Again, [progress](https://antonyjr.in/QArchive/docs/QArchiveDiskExtractor.html#void-progressqstring-file--int-processedentries--int-totalentries--qint64-bytesprocessed-qint64-bytestotal) signal is emitted with the progress, total entries and entries extracted if [setCalculateProgress(true)](https://antonyjr.in/QArchive/docs/QArchiveDiskExtractor.html#void-setcalculateprogressbool-choice) is set. 

Also you can get the total entries with [getinfo()](https://antonyjr.in/QArchive/docs/QArchiveDiskExtractor.html#void-infoqjsonobject-information) (You can count the no. of keys in the json object to get the total entries). As you can see the time taken for finding the total entries and file information is the same.

@unusual-aspect Did I get you wrong?? Please feel free to ask any other question.

**Comment by antony-jr** [comment]
@unusual-aspect You can get the no. of entries with getInfo(). Like this.

```
Extractor.getInfo();

int total = 0;
QObject::connect(&Extractor, &QArchive::DiskExtractor::info, [&](QJsonObject info) {
  total = info.size(); // Returns the no. of entries in the archive.
});

```

**Comment by antony-jr** [comment]
Also @unusual-aspect even if we implement a function to get the no. of entries and just return it. We would have to walk the entire archive which takes a lot of time based on the size of an archive. So with a async function like getInfo(), you won't block your GUI so that's why I'm not giving any sync functions. But you could make a simple function to do this sync too.

```
qint64 getEntries(const QString &archive) {
   qint64 r = 0;
   QArchive::DiskExtractor extractor(archive);
   QEventLoop loop;

   QObject::connect(&extractor, &QArchive::DiskExtractor::info,
   [&](QJsonObject info) {
      r = info.size();
      loop.quit();
   });
   extractor.getInfo();
   loop.exec();
   return r;
}
```
