### ISSUE TITLE
Add cmake install support

### ISSUE THREAD

**Issue by ericriff** [antony-jr/QArchive#34]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [X] Suggestion
- [ ] Other (please describe):

Hi!

I realized your library doesn't have `cmake install` support, which is pretty standar on CMake built libraries.
Do you mind adding it? 

Thanks!

**Comment by antony-jr** [comment]
I will look into this, Thanks for reporting.

**Comment by antony-jr** [comment]
@ericriff Done. Please test the latest commit in the master branch.

**Comment by ericriff** [comment]
It works correctly. Thanks for fixing this so quickly!
