### ISSUE TITLE
Undefined libarchive symbols

### ISSUE THREAD

**Issue by ericriff** [antony-jr/QArchive#35]
**Select your issue type:** (check at least one)
- [X] Bug
- [X] Question
- [X] Suggestion
- [ ] Other (please describe):

I'm building a small project using this library and I'm getting a lot of errors regarding undefined symbols that relate to `libArchive`
```
qarchivediskextractor_p.cc:(.text+0x209d): undefined reference to `archive_read_new'
qarchivediskextractor_p.cc:(.text+0x20cc): undefined reference to `archive_read_support_format_all'
qarchivediskextractor_p.cc:(.text+0x20d4): undefined reference to `archive_read_support_filter_all'
qarchivediskextractor_p.cc:(.text+0x20f3): undefined reference to `archive_read_open_fd'
qarchivediskextractor_p.cc:(.text+0x213b): undefined reference to `archive_read_next_header'
qarchivediskextractor_p.cc:(.text+0x2156): undefined reference to `archive_entry_pathname'
qarchivediskextractor_p.cc:(.text+0x218f): undefined reference to `archive_entry_stat'
qarchivediskextractor_p.cc:(.text+0x22a2): undefined reference to `archive_entry_filetype'
qarchivediskextractor_p.cc:(.text+0x3046): undefined reference to `archive_read_add_passphrase'
qarchivediskextractor_p.cc:(.text+0x360c): undefined reference to `archive_read_close'
qarchivediskextractor_p.cc:(.text+0x3616): undefined reference to `archive_read_free'
qarchivediskextractor_p.cc:(.text+0x3653): undefined reference to `archive_error_string'
qarchivediskextractor_p.cc:(.text+0x367a): undefined reference to `archive_read_close'
qarchivediskextractor_p.cc:(.text+0x3682): undefined reference to `archive_read_free'
qarchivediskextractor_p.cc:(.text+0x36e6): undefined reference to `archive_error_string'
qarchivediskextractor_p.cc:(.text+0x3721): undefined reference to `archive_read_close'
qarchivediskextractor_p.cc:(.text+0x372e): undefined reference to `archive_read_free'
```
Since I'm using this library through Conan (there is no official package, that is what I'm working on) I can easily do `self.requires.add("libarchive/3.4.0")`, which fixes my issues.
I'm wondering if your `CMakeLists.txt` should have a `find_package(LibArchive REQUIRED)` and `target_link_library(QArchive PUBLIC LibArchive::LibArchive)`. I'm no CMake expert so I may be talking out of place. 
Thanks!

**Comment by antony-jr** [comment]
Thanks for reporting this. Usually I just link with ```target_link_libraries(QArchive PUBLIC Qt5::Core archive)``` so I'm not using the CMake traditional way. I will look into this.

**Comment by ericriff** [comment]
I see. The difference is that by using the CMake find modules you get an early error if a given library, i.e. libArchive is not available or not found. That is because `find_package` is invoked during CMake's configure stage.
By contrast, they way you're instructing CMake to link it makes it possible to fail at linking stage, which is the last stage of the build.
I don't know how CMake handles finding a dependency if you don't use find_package.

**Comment by ericriff** [comment]
Consider:
```
--- CMakeLists.txt	2019-01-27 05:18:48.000000000 -0300
+++ CMakeLists_fix.txt	2021-03-01 13:59:19.868343390 -0300
@@ -12,7 +12,10 @@
 set(CMAKE_AUTOMOC ON)
 
 # Find the QtCore library.
-find_package(Qt5Core)
+find_package(Qt5Core REQUIRED)
+
+# Find the LibArchive library.
+find_package(LibArchive REQUIRED)
 
 # Include Directories.
 include_directories(.)
@@ -32,5 +35,5 @@
 	    include/qarchivediskextractor_p.hpp
 	    include/qarchiveutils_p.hpp)
 
-target_link_libraries(QArchive PUBLIC Qt5::Core archive)
+target_link_libraries(QArchive PUBLIC Qt5::Core LibArchive::LibArchive)
 target_include_directories(QArchive PUBLIC . include)

```

**Comment by antony-jr** [comment]
@ericriff Thanks. I've pushed the required changes in the latest commit in the master branch. Can you please test it?

**Comment by ericriff** [comment]
Amazing!
Please bump CMake minimum version to 3.17 since older versions do not support the scoped target for libArchive
```CMake
CMAKE_MINIMUM_REQUIRED( VERSION 3.17)
```

**Comment by ericriff** [comment]
After bumping the CMake minimum version, could you add a new release tag? :pray:

**Comment by antony-jr** [comment]
> After bumping the CMake minimum version, could you add a new release tag? pray

Sure. I'm currently migrating from Travis-CI. Would definitely do it after that.

**Comment by ericriff** [comment]
Awesome. Do you have an ETA?

**Comment by antony-jr** [comment]
> Awesome. Do you have an ETA?

10 minutes at max. I will ping you when it's done.

**Comment by antony-jr** [comment]
@ericriff More time needed than estimated but I've bumped the CMake version to 3.17, you can use [v2.0.1](https://github.com/antony-jr/QArchive/releases/tag/v2.0.1) release tag for the latest changes. Also adds [PVS Studio Analysis](https://antonyjr.in/QArchive/PVSStudioAnalysis/index.html) for the library.

**Comment by ericriff** [comment]
Awesome!
Thanks for the quick responses and fixes.
