### ISSUE TITLE
Error on Windows + shared

### ISSUE THREAD

**Issue by ericriff** [antony-jr/QArchive#37]
- [X] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

As I told you I've been working on packing your library with Conan. https://github.com/conan-io/conan-center-index/pull/4774
Conan CCI builds detected errors on Windows builds when using the shared version of the library, so I had to disable them for now.
The error we get is
```
 Checking Build System
test_package.obj : error LNK2019: unresolved external symbol "public: static struct QMetaObject const QArchive::DiskExtractor::staticMetaObject" (?staticMetaObject@DiskExtractor@QArchive@@2UQMetaObject@@B) referenced in function main [C:\J\w\cci_PR-4774@2\10\929e909f-cf7b-412c-9794-0b30057af34c\recipes\qarchive\all\test_package\build\dac7443591854e696bb8f2a41741d3eee515e674\test_package.vcxproj]
C:\J\w\cci_PR-4774@2\10\929e909f-cf7b-412c-9794-0b30057af34c\recipes\qarchive\all\test_package\build\dac7443591854e696bb8f2a41741d3eee515e674\bin\test_package.exe : fatal error LNK1120: 1 unresolved externals [C:\J\w\cci_PR-4774@2\10\929e909f-cf7b-412c-9794-0b30057af34c\recipes\qarchive\all\test_package\build\dac7443591854e696bb8f2a41741d3eee515e674\test_package.vcxproj]
```

Where `test_package.cpp` is the example code of your readme:

```
#include <QCoreApplication>
#include <QArchive/QArchive>

int main(int argc, char **argv)
{
    using QArchive::DiskExtractor;
    QCoreApplication app(argc, argv);
    DiskExtractor Extractor("Test.7z");

    /* Connect Signals and Slots. */
    QObject::connect(&Extractor ,
                     &DiskExtractor::finished ,
                     &app ,
                     &QCoreApplication::quit);

    Extractor.start();
    Extractor.cancel();

    return 0;
}
```

According to one of the devs in the conan community that error can happen because of some missing import/export directives
https://github.com/conan-io/conan-center-index/pull/4774#issuecomment-791241316

If you want to see the logs of the builds failing they are here
https://github.com/conan-io/conan-center-index/pull/4774#issuecomment-791079470

Thanks!

**Comment by antony-jr** [comment]
I never cared about Windows. Let me look into it.

**Comment by antony-jr** [comment]
@ericriff Can you try with release v2.0.2?

**Comment by antony-jr** [comment]
A more complete fix is in **v2.0.3** but I'm no windows expert, I just added the Q_DECL_IMPORT and Q_DECL_EXPORT as the user insisted.

**Comment by ericriff** [comment]
Awesome, thanks. 2.0.2 is being built in CCI. Lets see how it goes.

**Comment by antony-jr** [comment]
> Awesome, thanks. 2.0.2 is being built in CCI. Lets see how it goes. And then I'll try 2.0.3

More likely it will fail. Sorry.
