### ISSUE TITLE
Don't support chinese

### ISSUE THREAD

**Issue by winsoft666** [antony-jr/QArchive#49]
Compress `新建文件.txt` to zip, then extract to desktop, the filename is unreadable.

**Comment by antony-jr** [comment]
Thanks for reporting. I will look into this.

**Comment by winsoft666** [comment]
I has found a way to solve by adding below code to main function:
`setlocale(LC_ALL, ".936");`

But I don't know why?

**Comment by antony-jr** [comment]
Locale sets the region and language for the user. So I think what we have here is a locale error. I think we should manage locale from withing the library to handle all languages.

**Comment by antony-jr** [comment]
This related to https://github.com/libarchive/libarchive/issues/587

**Comment by Philippe91** [comment]
On windows, use archive_read_disk_open_w and not archive_read_disk_open

**Comment by antony-jr** [comment]
Yes, this issue is only seen in Windows. I tried this in Unix based OS, there is no problem handling Chinese characters. Need more testing.

**Comment by neheb** [comment]
Another way to fix this, at least for windows 10 and above, is to set the locale to utf8.

**Comment by antony-jr** [comment]
> Another way to fix this, at least for windows 10 and above, is to set the locale to utf8.

the solution is to use ```archive_entry_pathname_utf8``` and changing locale is never recommended, see https://github.com/libarchive/libarchive/issues/587#issuecomment-1207168664

Imagine multiple threads running code which uses locale, if we set locale just for our lib, it might mess every other lib the programmer uses and debugging that would be hell.

**Comment by neheb** [comment]
Windows 10 has an option to set UTF8 globally under Locale settings.

**Comment by antony-jr** [comment]
This issue is fixed, even multi-level utf-8 pathname (something like Дирек1/Другойрежиссер/Тест10.txt) are now supported in the master branch (soon will make a release). Thanks to @neheb for writing a extensive tests for windows to verify my fix, windows has always been hard to test.
