### ISSUE TITLE
Add zstd support

### ISSUE THREAD

**Issue by dprotti** [antony-jr/QArchive#53]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

QArchive is a wrapper around libarchive, a library which already supports [zstandard](https://en.wikipedia.org/wiki/Zstd) compression algorithm.
However QArchive does not include zstd among its QArchiveFormats. In our company we use zstd extensively so would be great to be able to use QArchive to handle this data format.

**Comment by antony-jr** [comment]
I've been working on this in the past days. The compression and extraction works but the memory based compression and extraction is not working well. I think there is some callbacks which I need to properly implement. (notably the archive_read_skip callback). Since some callbacks are crucial for different types of archives.

**Comment by dprotti** [comment]
Thank you very much for your work on this! I'll be happy once this work completes, and for sure many users of your library. Zstd is a great algorithm so would be a very valuable work to have it available on QArchive.

**Comment by moyamartin** [comment]
Hi Antony-jr, I am also interested in this issue. Are there any updates on this?

**Comment by antony-jr** [comment]
@moyamartin Yeah, almost complete. Only one test is failing in memory based extraction for zstd (I might be doing something wrong). Take a look at the progress in this new branch -> https://github.com/antony-jr/QArchive/tree/zstd

**Comment by antony-jr** [comment]
Yes. After a little bit of nitpicks.

**Comment by moyamartin** [comment]
Thanks @antony-jr let me know when you have a new release so I can update the dependency! Have a nice week

**Comment by antony-jr** [comment]
> Thanks @antony-jr let me know when you have a new release so I can update the dependency! Have a nice week

The latest release now has zstd support.

**Comment by dprotti** [comment]
@antony-jr thank you very much for your work on this!
We'll be integrating this new version soon to our systems and let you know how it goes.
