### ISSUE TITLE
Qt6 Support

### ISSUE THREAD

**Issue by evan-swinney** [antony-jr/QArchive#66]
**Select your issue type:** (check at least one)
- [ ] Bug
- [X] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Hello, I was trying to download QArchive through Conan for Qt 6, specifically Qt 6.4.1, but I cannot seem to get it to compile. I was wondering if this was because of a dependency on Qt 5.

I linked QArchive manually using the submodule approach and it works fine compiling on Qt 6.4.1; just not Conan. Is this a bug, or something else?

**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
@evan-swinney it seems like https://github.com/conan-io/conan-center-index/pull/14212 is pending, once that gets through you can get Qt6 support from the conan package itself, maybe we need add v2.2.3 which has even more improvements.

**Comment by antony-jr** [comment]
Use QArchive ```v2.2.3``` with your conan file, set the desired qt version for your application in your conan file. QArchive conan package will now support Qt6 just fine.
