### ISSUE TITLE
Build break under vs2015+windows10+qt5.6.3

### ISSUE THREAD

**Issue by hcaihao** [antony-jr/QArchive#7]
**Select your issue type:** (check at least one)
- [ x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
1>E:\Qt\QArchive\src\QArchive.cc(539): error C2065: 'ssize_t': undeclared identifier
1>E:\Qt\QArchive\src\QArchive.cc(539): error C2146: syntax error: missing ';' before identifier 'len'
1>E:\Qt\QArchive\src\QArchive.cc(539): error C2065: 'len': undeclared identifier
1>E:\Qt\QArchive\src\QArchive.cc(610): error C3861: 'open': identifier not found
1>E:\Qt\QArchive\src\QArchive.cc(611): error C2065: 'len': undeclared identifier
1>E:\Qt\QArchive\src\QArchive.cc(611): error C3861: 'read': identifier not found
1>E:\Qt\QArchive\src\QArchive.cc(612): error C2065: 'len': undeclared identifier
1>E:\Qt\QArchive\src\QArchive.cc(613): error C2065: 'len': undeclared identifier
1>E:\Qt\QArchive\src\QArchive.cc(614): error C2065: 'len': undeclared identifier
1>E:\Qt\QArchive\src\QArchive.cc(614): error C3861: 'read': identifier not found
1>E:\Qt\QArchive\src\QArchive.cc(616): error C3861: 'close': identifier not found

**Ways to Reproduce the issue (optional):**
After cmake , open the sln, build it,

**Comment by antony-jr** [comment]
I never built this in windows with msvc , did you have libarchive installed ?

**Comment by hcaihao** [comment]
Yes, Now I add

```
#if defined(_MSC_VER)

#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <io.h>
#include <stdio.h>
#include <BaseTsd.h>

typedef SSIZE_T ssize_t;

#endif
```

can solve this issue.

**Comment by antony-jr** [comment]
sounds good , I will update the source code with your fix! Thank You! :+1:
