### ISSUE TITLE
how to set destination path in compress process?

### ISSUE THREAD

**Issue by insar-dev** [antony-jr/QArchive#77]
**Select your issue type:** (check at least one)
- [x] Question

**Describe your issue:**

how to set destination path in compress process?
thanks.

**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
Do you mean the root directory or base directory?? Currently we don't have a ```setBasePath``` for compress, maybe we need to add that. For now the solution would be,

```
 auto basePath = "SomeDir/Path/"
 QArchive::DiskCompressor Compressor("Test.7z");
 
 Compressor.addFiles(/*Entry Name =*/ basePath + "/YourFile.txt", /*Path to Actual File in Disk=*/ "/actual/path/to/file.txt");

 Compressor.start()
```

Does that solve your question...
