### ISSUE TITLE
How to get file detail informations in the zip.

### ISSUE THREAD

**Issue by hcaihao** [antony-jr/QArchive#9]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
How to get file modify date, zipped size, original size, crc value? such as winrar does.

**Ways to Reproduce the issue (optional):**
Thanks.

**Comment by antony-jr** [comment]
@hcaihao These are not implemented yet , Sorry but I will get those features soon ( in a week or two ? ).

**Comment by hcaihao** [comment]
ok, expect for your work!
