### ISSUE TITLE
The latest release(2.2.5) can't be built against Qt 5.6.2. 

### ISSUE THREAD

**Issue by yosicovich** [antony-jr/QArchive#92]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
The latest release(2.2.5) can't be built against Qt 5.6.2. QString::back() was introduced in Qt 5.10. 
So, I would propose to implement conditional build or revert back the changes made.
The following commit has broken the build: effe5054b6c0659fae389b97a6a2fee448a43603
Compatibility with Qt 5.6.x is quite important since it is widely used in embedded development.
**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
Okay, I think I fixed it. Now we test all PRs with Qt 5.9.x, can't find easy way to use 5.6.x. But for now this will avoid merging future PRs which breaks the build with older Qt versions.

**Comment by yosicovich** [comment]
It is fine now. The only thing is tabs/spaces, see the picture
![изображение](https://user-images.githubusercontent.com/39350000/214407220-f5430ab9-4d96-4c1d-8fb2-1ba26a9ab322.png)
