### ISSUE TITLE
tests fail with latest libarchive

### ISSUE THREAD

**Issue by neheb** [antony-jr/QArchive#93]
- [x] Bug
- [x] Question

**Describe your issue:**
https://gist.github.com/neheb/f64fee33b0c5102413c0af2d8ba5eaff

**Ways to Reproduce the issue (optional):**
here's the thing about this failure. It's using the libarchive wrap and not the original CMake. There may be bugs.

The failures are all in QArchiveMemoryCompressorTests. No real idea why.

**Comment by antony-jr** [comment]
Let me confirm this.

**Comment by antony-jr** [comment]
@neheb can confirm this is a bug, https://github.com/antony-jr/QArchive/actions/runs/6525130099/job/17717498291

Seems like a Qt 6.5.x specific bug.

**Comment by antony-jr** [comment]
Seems like Qt 6.5.x is now imposing strict types, so I can't invoke a QIODevice* object as QObject*.

**Comment by antony-jr** [comment]
Thanks for reporting this @neheb, it seems we need to run the tests every week or so  to find these kind of bugs early on. Reopen this issue if you still face this bug.
