### ISSUE TITLE
custom suffix format.

### ISSUE THREAD

**Issue by Alvazz** [antony-jr/QArchive#97]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

Is it possible to support compression of a custom suffix format? For example, I compress a folder named "test" into "test.myfiledata", and then decompress the "test.myfiledata" file to finally get the initial "test" folder.

**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
Yes you can, [it's mentioned here in the official documentation](https://www.antonyjr.in/QArchive/docs/QArchiveDiskCompressor.html#void-setarchiveformatshort-archiveformat).
